app:
  secret:               {{ settings_app_secret }}
  domain:               {{ settings_app_domain }}
  host:                 {{ settings_app_host }}
  url:                  {{ settings_app_url }}

profile:
  url:                  {{ settings_profile_url }}
  sign_in_url:          {{ settings_profile_sign_in_url }}
  sign_out_url:         {{ settings_profile_sign_out_url }}

redis:
  url:                  {{ settings_redis_url }}

session_store:
  db:                   {{ settings_session_store_db }}
  key_prefix:           {{ settings_session_store_key_prefix }}
  host:                 {{ settings_session_store_host }}
  port:                 {{ settings_session_store_port }}

redis_user_connector:
  url:                  {{ settings_redis_user_connector_url }}

smtp:
  address:              {{ settings_smtp_address }}
  authentication:       {{ settings_smtp_authentication }}
  port:                 {{ settings_smtp_port }}
  user_name:            {{ settings_smtp_user_name }}
  password:             {{ settings_smtp_password }}

solr:
  url:                  {{ settings_solr_url }}

errors:
  key:                  {{ settings_errors_key }}
  url:                  {{ settings_errors_url }}

